apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-entity
  description: Github Entity
  annotations:
    pagerduty.com/service-id: P18JCJH
    pagerduty.com/integration-key: dsadsadsadsadsadsa
    sonarqube.org/project-key: test-project-key
    datadoghq.com/service-id: test-service-id
    backstage.io/kubernetes-id: soundcheck-test-service
    atlassian.net/jql: project = "SCRUM"
  tags:
    - github
    - k8s
spec:
  type: service
  lifecycle: production
  owner: toast-infra
  system: soundcheck
  dependsOn:
    - resource:default/gke-test-cluster-1
