apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-repo
  description: Github Demo Component
  annotations:
    pagerduty.com/integration-key: dsadsadsadsadsadsa
  tags:
    - internal
spec:
  type: website
  lifecycle: experimental
  owner: toast-infra
  system: soundcheck
