apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-entity
  description: Github Entity
  annotations:
    # pagerduty.com/service-id: P18JCJH
    # pagerduty.com/service-id: P9TSZZ5 # uncomment
    # pagerduty.com/integration-key: a47161262f244a92b04029c7a4a8e263 # uncomment
    # sonarqube.org/project-key: test-project-key
    sonarqube.org/organization-key: kklymkovska
    sonarqube.org/project-key: kklymkovska_soundcheck-demo
    datadoghq.com/service-id: test-service-id
    backstage.io/kubernetes-id: soundcheck-test-service
    atlassian.net/jql: project = "SCRUM"
  labels:
    version: 8.11.3
  tags:
    - github
spec:
  type: service
  lifecycle: production
  owner: toast-infra
  system: soundcheck
  dependsOn:
    - resource:default/gke-test-cluster-1
