apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soundcheck-demo
  description: Soundcheck Demo Component
  annotations:
    pagerduty.com/integration-key: dsadsadsadsadsadsa
  tags:
    - external
spec:
  type: website
  lifecycle: experimental
  owner: toast-infra
  system: soundcheck
